---
output:
  html_document: default
  pdf_document: default
---
# User study Intelligent Task Management and Visualisation: Evaluation

## Task 1.1 - Extended Nasa-TLX
```{r}
getwd()
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)

nasa_tlx <- read_excel("data/data_prepared.xlsx", sheet="task_1_ext_nasa_tlx")

data <- nasa_tlx %>%
  pivot_longer(cols = c(`Workload`, `Sense of control`, `Creativity Support Index`), names_to="variable", values_to="value") %>%
  group_by(variable) %>%
  summarize_at(vars(value), list(~mean(.), ~sd(.))) %>%
  arrange(factor(variable, levels = c("Workload", "Sense of control", "Creativity Support Index")))


plot <- data %>%
  ggplot( aes(x=factor(variable, level=variable), y=mean, fill=variable)) + 
  geom_bar(position="dodge", stat="identity", colour = "#000000") + 
  geom_errorbar(aes(x=variable, ymin=mean-sd, ymax=mean+sd), width=0.2) + 
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100), limits=c(0,100)) +
  xlab(" ") + ylab("Mean") +
  guides(fill="none") +
  theme_minimal() +
  scale_fill_brewer(palette = "Blues")

print(plot)

ggsave("plots/bar_nasa_tlx.eps",
       plot = plot,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
```

# Task 1.1 - Number of events by prior experience 
```{r}
getwd()
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)

events <- read_excel("data/data_prepared.xlsx", sheet="task_1_events")

data <- events %>%
  pivot_longer(cols=c(4:11), names_to="variable", values_to="value") %>%
  group_by(`Used before`, variable) %>%
  summarise_at(vars(value), list(~mean(.), ~sd(.)))

plot <- data %>%
  ggplot(aes(x=reorder(variable, -mean), y=mean, fill=factor(`Used before`))) + 
  geom_bar(stat="identity", position = "dodge") + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=0.2, position=position_dodge(.9)) + 
  xlab("Event type") + ylab("Events") +
  theme_minimal() +
  theme(legend.position="top") + 
  scale_fill_manual(values=c("#F87171", "#34D399"), 
                    name="Have you used board based tools before?",
                    labels=c("no (n=3)", "yes (n=10)"))
print(plot)

ggsave("plots/bar_events_by_exp.eps",
       plot = plot,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
```

## Task 1.2 Correlation experience -> number of events
```{r}
getwd()
library(readxl)
events <- read_excel("data/data_prepared.xlsx", sheet="task_1_events")

c1 <- cor.test(events$`Used before`, events$`All events`)
c2 <-cor.test(events$`Used before`, events$move)
c3 <- cor.test(events$`Used before`, events$create)

c4 <- cor.test(events$`Prior experience`, events$`All events`)
c5 <- cor.test(events$`Prior experience`, events$move)
c6 <- cor.test(events$`Prior experience`, events$create)
```

## Task 1.2 - Nesting comparision
```{r}
getwd()
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)

level <- read_excel("data/data_prepared.xlsx", sheet="task_1_level")

data <- level %>% pivot_longer(cols=-c(`Participant ID`), names_to="variable", values_to="value") %>% 
  group_by(variable) %>% 
  summarize_at(vars(value), list(~mean(.), ~sd(.))) %>%
  arrange(factor(variable, levels = c("Standard", "Personal", "Favourite of proposed", "Favourite overall")))

plot <- data %>%
  ggplot(aes(x=factor(variable, level=variable), y=mean, fill=variable)) + 
  geom_bar(stat="identity", position = "dodge", colour = "#000000") + 
  geom_errorbar(aes(x=variable, ymin=mean-sd, ymax=mean+sd), width=0.2) + 
  xlab("Arrangement") + ylab("Nesting level") +
  guides(fill="none") +
  theme_minimal() +
  scale_fill_brewer(palette = "Blues")

print(plot)

ggsave("plots/bar_levels.eps",
       plot = plot,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
```
```{r}
getwd()
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(waffle)
library(scales)

favourite <- read_excel("data/data_prepared.xlsx", sheet="task_1_favourite")

data1 <- favourite %>%
  count(`Favourite of proposed`, sort=TRUE) %>%
  mutate(freq = percent(n / sum(n))) %>%
  unite(col=label , `Favourite of proposed`, freq , sep = ", ") %>%
  pull(n, label)

data2 <- favourite %>%
  count(`Favourite overall`, sort=TRUE) %>%
  mutate(freq = percent(n / sum(n))) %>%
  unite(col=label , `Favourite overall`, freq , sep = ", ") %>%
  pull(n, label)

plot1 <- waffle(data1, rows=1)
plot2 <- waffle(data2, rows=1)

plot1
plot2

ggsave("plots/waffle_favourite_of_proposed.eps",
       plot = plot1,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       height = 4,
       limitsize = TRUE)

ggsave("plots/waffle_favourite_overall.eps",
       plot = plot2,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       height = 4,
       limitsize = TRUE)

```


## Task 2 - Manual scheduling evaluation
```{r}
getwd()
library(readxl)
library(reshape2)
library(ggplot2)

diff_h <- read_excel("data/data_prepared.xlsx", sheet="task_2_diff_h")
diff_due <- read_excel("data/data_prepared.xlsx", sheet="task_2_diff_due")
diff_order <- read_excel("data/data_prepared.xlsx", sheet="task_2_diff_order")

data_h <- melt(diff_h, id.vars=c("Participant ID", "Type"))
data_due <- melt(diff_due, id.vars=c("Participant ID", "Type"))
data_order <- melt(diff_order, id.vars=c("Participant ID", "Type"))

plot_h <- data_h %>%
  ggplot(aes(x=factor(Type, level=unique(Type)), y=value, fill=variable)) + 
  geom_boxplot() + 
  # geom_jitter() +
  xlab("Error type") + ylab("Working hours") + 
  theme_minimal() + 
  theme(legend.title = element_blank()) +
  scale_fill_brewer(palette = "Blues")

plot_due <- data_due %>%
  ggplot(aes(x=factor(Type, level=unique(Type)), y=value, fill=variable)) + 
  geom_boxplot() + 
  # geom_jitter() +
  xlab("Error type") + ylab("Missed due dates") +
  theme_minimal() + 
  theme(legend.title = element_blank()) +
  scale_fill_brewer(palette = "Blues")

plot_order <- data_order %>%
  ggplot(aes(x=factor(Type, level=unique(Type)), y=value, fill=variable)) + 
  geom_boxplot() + 
  # geom_jitter() +
  scale_y_continuous(breaks = c(.2, .4, .6, .8, 1), limits=c(0,1)) +
  xlab("Similarity of manual order") + ylab("Similarity measure") + 
  theme_minimal() + 
  theme(legend.title = element_blank()) +
  scale_fill_brewer(palette = "Blues")

plot_h
plot_due
plot_order

ggsave("plots/box_diff_h.eps",
       plot = plot_h,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
ggsave("plots/box_diff_due.eps",
       plot = plot_due,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
ggsave("plots/box_diff_order.eps",
       plot = plot_order,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
```
## Task 1 - Likert type questions
```{r}
library(dplyr)
library(readxl)
library(likert)

likert1 <- read_excel("data/data_prepared.xlsx", sheet="likert_1")
likert1 <- likert1 %>% select(-c(`Participant ID`))

questions <- c(
  "I understood what my task was about.", 
  "The software supported me visualizing the project.", 
  "The arrangement I created matches my mental image of the project."
  )

data <- likert1 %>%
    mutate_all(~dplyr::recode(., `1` = "Strongly disagree", `2` = "Disagree", `3` = "Neutral", `4` = "Agree", `5` = "Strongly agree")) %>%
    lapply(factor, levels= c("Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"), ordered = TRUE) %>%
    as.data.frame()  %>% 
  rename(
      !!questions[1] := "LTQ1A",
      !!questions[2] := "LTQ1B",
      !!questions[3] := "LTQ1C"
    ) 



plot <- likert(data) %>%
  likert.bar.plot(wrap=25, group.order = names(data)) +
  theme_minimal() + 
  theme(axis.text.y = element_text(size = 8), legend.position = "bottom", legend.text=element_text(size = 8))

plot(plot)

ggsave("plots/likert_1.eps",
       plot = plot,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
```

## Task 2 - Likert type questions
```{r}
library(dplyr)
library(readxl)
library(likert)

likert2 <- read_excel("data/data_prepared.xlsx", sheet="likert_2")
likert2 <- likert2 %>% select(-c(`Participant ID`))

questions <- c(
  "I feel patronized by the software making the planning for me.",
  "I find the proposal easy to perceive.",
  "I find the proposal intelligable.",
  "I trust the proposal to be better than my manual planning.",
  "I would find an automatic planning feature like this to be helpful.",
  "It is likely that I would use an automatic planning feature like this.",
  "If my privacy is guaranteed, I am generally open to intelligent features in a software like this."
  )

data <- likert2 %>%
    mutate_all(~dplyr::recode(., `1` = "Strongly disagree", `2` = "Disagree", `3` = "Neutral", `4` = "Agree", `5` = "Strongly agree")) %>%
    lapply(factor, levels= c("Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree")) %>%
    as.data.frame()  %>% 
  rename(
      !!questions[1] := "LTQ2A",
      !!questions[2] := "LTQ2B",
      !!questions[3] := "LTQ2C",
      !!questions[4] := "LTQ2D",
      !!questions[5] := "LTQ2E",      
      !!questions[6] := "LTQ2F",
      !!questions[7] := "LTQ2G",
    ) 

plot <- likert(data) %>%
  likert.bar.plot(wrap=30, ordered=FALSE, group.order=names(data)) +
  theme_minimal() + 
  theme(axis.text.y = element_text(size = 8), legend.position = "bottom", legend.text=element_text(size = 8))

print(plot)

ggsave("plots/likert_2.eps",
       plot = plot,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
```

## General - Likert type questions
```{r}
library(dplyr)
library(readxl)
library(likert)

likert3 <- read_excel("data/data_prepared.xlsx", sheet="likert_3")
likert3 <- likert3 %>% select(-c(`Participant ID`))

questions <- c(
  "I found the interface of the software easy to understand.",
  "The features of the software were clear to me. I understand what can be done using the features.",
  "I liked the possibility to arrange elements (boards, lists, items) in an arbitrarily nested way."
  )

data <- likert3 %>%
    mutate_all(~dplyr::recode(., `1` = "Strongly disagree", `2` = "Disagree", `3` = "Neutral", `4` = "Agree", `5` = "Strongly agree")) %>%
    lapply(factor, levels= c("Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"), ordered = TRUE) %>%
    as.data.frame()  %>% 
  rename(
      !!questions[1] := "LTQ3A",
      !!questions[2] := "LTQ3B",
      !!questions[3] := "LTQ3C"
    ) 



plot <- likert(data) %>%
  likert.bar.plot(wrap=25, group.order = names(data)) +
  theme_minimal() + 
  theme(axis.text.y = element_text(size = 8), legend.position = "bottom", legend.text=element_text(size = 8))

plot(plot)

ggsave("plots/likert_3.eps",
       plot = plot,
       device = "eps",
       scale = 1, units = "cm",
       dpi = 300,
       limitsize = TRUE)
```
